CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    price REAL NOT NULL CHECK (price > 0),
    stock INTEGER NOT NULL,
    category TEXT NOT NULL,
    sku TEXT NOT NULL UNIQUE,
    size TEXT NOT NULL
);